In [31]:
from qiskit.circuit import Parameter, QuantumCircuit
from qiskit.primitives import StatevectorEstimator
from qiskit.quantum_info import Pauli, SparsePauliOp
from qiskit.circuit import library
 
import matplotlib.pyplot as plt
import numpy as np


In [32]:
expectation_values = []

zgate = np.array([
    [1, 0],
    [0, -1]
])

igate = np.array([
    [1, 0],
    [0, 1]
])


z0z1 = np.kron(np.kron(zgate, zgate), igate)
z0z2 = np.kron(np.kron(zgate, igate), zgate)
observable = z0z1 + z0z2
print(observable)

observables = [
    [SparsePauliOp.from_operator(observable)]
]

labels = ["000", "001", "010", "011", "100", "101", "110", "111"]
for i in labels:
    circuit = QuantumCircuit(3)
    circuit.initialize(i)

    estimator = StatevectorEstimator()
    
    
    pub = (circuit, observables)
    job = estimator.run([pub])
    
    # Extract the result for the 0th pub (this example only has one pub).
    result = job.result()[0]

    for idx, pauli in enumerate(observables):
        expectation_values += [result.data.evs[idx][0]]

print(expectation_values)


[[ 2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0 -2  0  0  0  0]
 [ 0  0  0  0 -2  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  2]]
[2.0, 0.0, 0.0, -2.0, -2.0, 0.0, 0.0, 2.0]


In [33]:
sums = []

for i in range(8):
    z0 = 1 if i & 1 != 0 else -1
    z1 = 1 if i & 2 != 0 else -1
    z2 = 1 if i & 4 != 0 else -1

    print(z0, z1, z2)

    sums += [z0 * z1 + z0 * z2]

print(sums)


-1 -1 -1
1 -1 -1
-1 1 -1
1 1 -1
-1 -1 1
1 -1 1
-1 1 1
1 1 1
[2, -2, 0, 0, 0, 0, -2, 2]
