In [4]:
import numpy as np

In [5]:
f = np.array([[0],[1]])
g = np.array([[1/np.sqrt(2)],[1j/np.sqrt(2)]])

sigmax = np.array([[0, 1], [1, 0]])

print('f = \n', f, '\n')
print('g = \n', g, '\n')
print('sigmax = \n', sigmax ,'\n')

f = 
 [[0]
 [1]] 

g = 
 [[0.70710678+0.j        ]
 [0.        +0.70710678j]] 

sigmax = 
 [[0 1]
 [1 0]] 



In [6]:
print('np.matmul(sigmax,f) = \n', np.matmul(sigmax,f) ,'\n')
print('np.matmul(sigmax,g) = \n', np.matmul(sigmax,g) ,'\n')
print('np.kron(np.matmul(sigmax,f), np.matmul(sigmax,g)) = \n', np.kron(np.matmul(sigmax,f), np.matmul(sigmax,g)) ,'\n')

np.matmul(sigmax,f) = 
 [[1]
 [0]] 

np.matmul(sigmax,g) = 
 [[0.        +0.70710678j]
 [0.70710678+0.j        ]] 

np.kron(np.matmul(sigmax,f), np.matmul(sigmax,g)) = 
 [[0.        +0.70710678j]
 [0.70710678+0.j        ]
 [0.        +0.j        ]
 [0.        +0.j        ]] 



In [7]:
print('np.kron(sigmax, sigmax) = \n', np.kron(sigmax, sigmax) ,'\n')
print('np.kron(f,g) = \n', np.kron(f,g) ,'\n')
print('np.matmul(np.kron(sigmax, sigmax), np.kron(f,g)) = \n', np.matmul(np.kron(sigmax, sigmax), np.kron(f,g)) ,'\n')

np.kron(sigmax, sigmax) = 
 [[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]] 

np.kron(f,g) = 
 [[0.        +0.j        ]
 [0.        +0.j        ]
 [0.70710678+0.j        ]
 [0.        +0.70710678j]] 

np.matmul(np.kron(sigmax, sigmax), np.kron(f,g)) = 
 [[0.        +0.70710678j]
 [0.70710678+0.j        ]
 [0.        +0.j        ]
 [0.        +0.j        ]] 

