In [13]:
import numpy as np

In [14]:
# 15.1

u_not = np.array([[0, 1], [1, 0]])

print('inverse of u_not :\n', np.linalg.inv(u_not))
print('adjoint (conjugate transpose) of u_not :\n', np.transpose(np.conjugate(u_not)))

inverse of u_not :
 [[0. 1.]
 [1. 0.]]
adjoint (conjugate transpose) of u_not :
 [[0 1]
 [1 0]]


In [15]:
# 15.2

u_cnot = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])

print('inverse of u_cnot :\n', np.linalg.inv(u_cnot))
print('adjoint (conjugate transpose) of u_cnot :\n', np.transpose(np.conjugate(u_cnot)))

inverse of u_cnot :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
adjoint (conjugate transpose) of u_cnot :
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
